[project]
name = "dagsordener"
version = "0.1.0"
description = "Prototype for improved indexing of dagsordener.aarhus.dk data"
requires-python = ">=3.10, <=3.12"
dependencies = [
  "torch",
  "playwright",
  "httpx",
  "beautifulsoup4",
  "markdownify",
  "FlagEmbedding",
  "qdrant-client",
  "pydantic",
]

[tool.ruff]
line-length = 100
lint.select = ["E","F","I","UP"]
format.quote-style = "single"

[tool.uv]
index-strategy = "unsafe-best-match"
